language: android
dist: precise
sudo: false

os:
  - linux
  - osx
  
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-25
    - addon-google-apis-google-25
    - sys-img-armeabi-v7a-google_apis-25
    - sys-img-armeabi-v7a-addon-google_apis-google-25
env:
  matrix:
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a TAG=default
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a TAG=google_apis

before_script:
  # Create and start emulator
  - jdk_switcher use oraclejdk8
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi "${TAG}/${ANDROID_ABI}" --tag $TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - while [[ `adb shell pm path android` == 'Error'* ]]; do sleep 2; done
  - adb shell input keyevent 82 &

script: ./gradlew --info lint connectedAndroidTest
