language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-15
    - android-21
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-15

env:
  matrix:
    - ANDROID_TARGET=android-15 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=5 # increase from default of 2 mins

before_script:
  # Create and start emulator
  - android list targets
  - jdk_switcher use oraclejdk8
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew lint connectedCheck

sudo: false
