language: android
dist: precise

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - build-tools-25.0.2
    - android-4
    - android-10
    - android-19
    - android-23
    - android-24
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24
    - addon-google-apis-google-24
    - sys-img-armeabi-v7a-google_apis-24
    - sys-img-armeabi-v7a-addon-google_apis-google-24
    - sys-img-armeabi-v7a-android-25
    - addon-google-apis-google-25
    - sys-img-armeabi-v7a-google_apis-25
    - sys-img-armeabi-v7a-addon-google_apis-google-25
env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a TAG=default
    - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a TAG=default
    - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a TAG=google_apis
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a TAG=default
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a TAG=google_apis



before_script:
  # Create and start emulator
  - jdk_switcher use oraclejdk8
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi "${TAG}/${ANDROID_ABI}" --tag $TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - while [[ `adb shell pm path android` == 'Error'* ]]; do sleep 2; done
  - adb shell input keyevent 82 &

script: ./gradlew --info lint connectedAndroidTest

sudo: false
